### ISSUE TITLE
"This tour is no longer supported" alert is positioned in the wrong place

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#2839]
**Describe the bug**
If you try to access a tour story that no longer exists, an alert should show up saying "Sorry, this tour is no longer supported" below the 4 buttons in the upper right corner, and disappear in 10 seconds. The alert instead appears at the top of the page, so it's difficult to see. 

**To Reproduce**
1. Go to a fake tour/tour that does not exist
2. See error - alert is at the top of the page. 

**Expected behavior**
The alert should appear in the same positioning as the Events alert and the comparison mode alert - under the 4 buttons in the upper right corner. 

**Screenshots**

<img width="1435" alt="Screen Shot 2020-04-16 at 12 29 27 PM" src="https://user-images.githubusercontent.com/10747923/79485153-bd17a000-7fe2-11ea-833e-37d249f75639.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome, Firefox

**Comment by Benjaki2** [comment]
This looks fixed in `3.7` on `develop`

**Comment by minniewong** [comment]
The alert still appears at the top of the page, making it difficult to see. It should appear where other similar alerts appear (under the icons in the upper right)
