### ISSUE TITLE
Product picker info buttons expand multiple layers at once.

### ISSUE THREAD

**Issue by localjo** [nasa-gibs/worldview#624]
Sometimes clicking on the info buttons to expand layer information expands more than one layer at a time;
<img width="983" alt="screen shot 2017-11-30 at 5 02 56 pm" src="https://user-images.githubusercontent.com/516388/33457540-c478d1e6-d5f0-11e7-91bb-2b45797ad16d.png">

You have to click around on a few info buttons to see the effect, since it doesn't always happen.

**Comment by edplato** [comment]
Unable to reproduce in Chrome, IE11, Firefox. I have definitely seen the issue a few versions ago, but may have been fixed in Bootstrap 4/Reactstrap upgrade or June 1 layer list fix.

**Comment by minniewong** [comment]
I still see this in Chrome OSX. Click on a few info buttons, then close them, then open another further below those initial ones, and they all open.
